server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: elaparato
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/el-aparato-palermo # cambie puerto 9090 al de keycloack
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    username: kike
    url: jdbc:mysql://localhost:3366/elaparato?serverTimezone=UTC
    password: '1234'

jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: el-aparato-gateway

dh:
  keycloak:
    serverUrl: http://localhost:8080
    realm: el-aparato-palermo
    clientId: el-aparato-client
    clientSecret: q88t0MnMzrimj1prnqliSNq0v5dZDfsA
